sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dvelez/web -f Dockerfile.dev .

script:
  - docker run -e CI=true dvelez/web npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "web"
  env: "Web-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-070071872053"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY