sudo: required
language: node_js
node_js:
  - stable

services:
  - docker

before_install:
  - docker build -t dvelez/web -f Dockerfile.dev .

script:
  - docker run -e CI=true dvelez/web npm run test -- --coverage

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "new-web"
  env: "new-web-env"
  bucket_name: "elasticbeanstalk-us-east-1-070071872053"
  bucket_path: "new-web"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY